### ISSUE TITLE
Getting "No route to host (os error 65)"

### ISSUE THREAD

**Issue by pfr-dev** [xvxx/phetch#19]
Getting "No route to host (os error 65)" when trying to visit gopher://g.nixers.net either from bookmarks or direct from the command line. 

<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/9MKfzNsk/09-28-2020-11-29.png' border='0' alt='09-28-2020-11-29'/></a>

<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/65R84tWf/09-28-2020-11-17.png' border='0' alt='09-28-2020-11-17'/></a>

I am able to access this particular gopherhole using Lynx so the issue seems to be with phetch. Any idea what's going on here?

I'm on NetBSD in case the error relates to the "OS"

**Comment by xvxx** [comment]
Hi there, sorry about this. Does this error message only appear for that specific host, or does it happen trying to use phetch at all?

**Comment by pfr-dev** [comment]
Yes, it is only for this particular host, using phetch on NetBSD. I have another laptop running Pop!_OS LInux and am able to access this host with no errors. 
The strange thing is this error came out of nowhere. I was able to access this host from my NetBSD machine just fine until all of a sudden I couldn't. 
I reached out to the sysadmin for g.nixers.net and they informed me they had recently configured ipv6 stack on the server, adding  a AAAA record for g.nixers.net. But seeing as I can access this host using Lynx from my NetBSD system it doesn't appear to be an issue with ipv6.

I don't get this error for any other hosts afaik.

**Comment by pfr-dev** [comment]
Just an update. I asked about this in [another forum](https://www.unitedbsd.com/d/264/16) and it appears that the issue is around accessing ipv6. 

As user **rpv** suggests in that thread, it would appear that `phetch` does not try to connect to other IP's if the first one fails. 

Could this functionality possible be added at some point?

**Comment by xvxx** [comment]
I have to apologize, I don't know much about IPv6 at all. But wise **rvp's** words ring true -- the `socket_addrs()` call phetch makes does indeed return a list that I'm not properly caring for.

I've just updated the code to go through the list and try each entry instead of aborting entirely if the first one fails. Is it possible for you to build from `master` and try it out?

If not that's fine, I'm working on getting a NetBSD instance going on EC2 and should be able to use that for testing in the near future.

Sorry about this bug! And thanks for pointing me to the forum thread, it's very helpful.

**Comment by ghost** [comment]
@xvxx Cool that you are working on getting NetBSD running :)
But you don't need to do it for this issue. I've just did a git-master package of `phetch` to test and its working now.
Check back at the forum thread for a screenshot ;)

This is nothing I can import into the main repo, though. Only stable releases are allowed by default but, at least I know it will be fixed by the next one.
Cheers for your collaborative spirit and feel free to close this issue.

**Comment by xvxx** [comment]
@voidpin Awesome, thank you so much! I've just pushed out v1.0.7 with this fix. Appreciate the help, everyone!

**Comment by ghost** [comment]
@xvxx Thx! https://mail-index.netbsd.org/pkgsrc-changes/2020/10/03/msg222089.html
;)

**Comment by pfr-dev** [comment]
@xvxx & @voidpin thank you both very much 😊
